endpoint: https://samsaradev.atlassian.net
editor: vim
user: Shane Schulte
login: shane.schulte@samsara.com

custom-commands:
  - name: mysprint
    help: display issues assigned to me in my current sprint
    script: |-
      {{jira}} list --query "resolution = unresolved and status NOT IN ('In Review', 'Merged', 'Archive') and assignee=currentuser() and sprint in openSprints() ORDER BY priority,created"

  - name: mine
    help: display issues assigned to me
    script: |-
      {{jira}} list --query "resolution = unresolved and status NOT IN ('In Review', 'Merged', 'Archive') and assignee=currentuser() ORDER BY priority,created"

  - name: current-sprint
    help: gets the currently active sprint ID
    args:
      - name: PROJECT
        required: true
    script: |
      board_id=$({{jira}} req "/rest/agile/1.0/board?projectKeyOrId={{args.PROJECT}}" --gjq values.0.id)
      {{jira}} req "/rest/agile/1.0/board/$board_id/sprint?state=active" --gjq values.0.id
