endpoint: https://samsaradev.atlassian.net
editor: vim
user: Shane Schulte
login: shane.schulte@samsara.com

custom-commands:
  - name: mysprint
    help: display issues assigned to me in my current sprint
    script: |-
      {{jira}} list --query "resolution = unresolved and status NOT IN ('Merged', 'Archive') and assignee=currentuser() and sprint in openSprints() ORDER BY priority,created"

  - name: unstarted
    help: display issues assigned to me that I haven't started
    script: |-
      {{jira}} list --query "resolution = unresolved and status NOT IN ('Merged', 'Archive') and assignee=currentuser() and sprint in openSprints() ORDER BY priority,created"

  - name: mine
    help: display issues assigned to me
    script: |-
      {{jira}} list --query "resolution = unresolved and status NOT IN ('Merged', 'Archive') and assignee=currentuser() ORDER BY priority,created"

  - name: all
    help: display all issues
    script: |-
      {{jira}} list --query "resolution = unresolved and project = admn and ORDER BY created"

  - name: lbacklog
    help: display all backlog'd issues
    script: |-
      {{jira}} list --query "resolution = unresolved and project = admn and status = 'Backlog' ORDER BY created"
